[package]
name = "midi"
version = "0.1.0"
edition = "2024"

[lib]
name = "midi"
path = "src/lib.rs"

[[bin]]
name = "midi"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
cpal = "0.18.1"
crossterm = "0.29.0"
hound = "3.5.1"
midly = "0.5.3"
mp3lame-encoder = "0.2.4"
ratatui = "0.30.2"
rustysynth = "1.3.6"

[profile.dev]
opt-level = 2
